version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main.py
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0 --reload
