# name: Github-Pages

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v1
#         # with:
#         #   submodules: false

#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: '0.92.2'
#           extended: true

#       - name: Build
#         working-directory: ./
#         # --cleanDestinationDir 清除舊檔案
#         run: hugo --minify --gc --cleanDestinationDir

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.DEPLOY_GITHUB_PAGE_SECRET }}
#           publish_branch: gh_pages
#           force_orphan: true

#       - name: cleanup files of public site
#         shell: bash
#         run: rm -rf public

# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.DEPLOY_GITHUB_PAGE_SECRET }}
          # Or if publishing to the same repo, use the automatic token
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}